export enum ErrorCode {
  // General codes
  INVALID_DATA = 'P1000',
  INTERNAL_SERVER_ERROR = 'P1001',
  UNAUTHORIZED = 'P1002',
  FORBIDDEN = 'P1003',

  // The codes for the auth app
  USER_ALREADY_EXISTS = 'P2000',
  USER_NOT_FOUND = 'P2001',
  INVALID_SOCIAL_AUTH_CODE = 'P2002',
  INVALID_ACTIVATION_TOKEN = 'P2003',
  ACCOUNT_CREATED_VIA_ANOTHER_METHOD = 'P2004',
  RESET_PASSWORD_IMPOSSIBLE = 'P2005',
  INVALID_RESET_CODE = 'P2006',
  ERROR_PASSWORD_UPDATE_EXTERNAL_ACCOUNT = 'P2007',
  USER_NOT_LOGGED = 'P2008',
  INVALID_TWO_FACTOR_AUTH_CODE = 'P2009',
  EXCEEDED_MAXIMUM_NUMBER_OF_ATTEMPTS_FOR_TWO_FACTOR_AUTH = 'P2010',
  USER_ALREADY_EXIST = 'P2011',
  USER_ALREADY_LOGGED = 'P2012',

  // The codes for the tokens app
  INVALID_JWT = 'P3000',

  // The codes for the users app
  INVALID_PASSWORD = 'P4000',
  INSUFFICIENT_PERMISSION = 'P4001',
  TEAM_NOT_FOUND = 'P4002',
  TEAM_ALREADY_EXISTS = 'P4003',

  // The codes for the notifications app
  NOTIFICATION_NOT_FOUND = 'P4900',
  NOTIFICATION_TOKEN_NOT_FOUND = 'P4901',
  TOKEN_NOT_FOUND = 'P4902',
  MISSING_USER_TARGET = 'P4903',

  // The codes for the meta pixel events app
  EVENT_NOT_PROCESSED = 'P2050',

  // The codes for the logs app
  LOGS_NOT_FOUND = 'P2200',

  // The codes for the firebase app
  FCM_SEND_ERROR = 'P4800',

  // The codes for the reviews app
  REVIEW_NOT_FOUND = 'P1500',
  REVIEW_ALREADY_EXISTS = 'P1501',

  // The codes for the events app
  EVENT_ALREADY_EXISTS = 'P2700',
  EVENT_NOT_FOUND = 'P2701',

  // The codes for the work sessions app
  WORK_SESSION_NOT_FOUND = 'P2500',
  WORK_SESSION_ALREADY_OPEN = 'P2501',
  WORK_DAY_NOT_FOUND = 'P2502',

  // The codes for the server app
  SERVER_NOT_FOUND = 'P2600',
  SERVER_ALREADY_EXISTS = 'P2601',
  SERVICE_NOT_FOUND = 'P2602',
  SERVICE_ALREADY_EXISTS = 'P2603',

  // The codes for the personal tasks app
  PERSONAL_TASK_NOT_FOUND = 'P5000',
  PERSONAL_TASK_COMMENT_NOT_FOUND = 'P5001',

  // The codes for the projects app
  PROJECT_NOT_FOUND = 'P6000',
  PROJECT_ALREADY_EXISTS = 'P6001',
  PROJECT_MEMBER_NOT_FOUND = 'P6002',
  PROJECT_MEMBER_ALREADY_EXISTS = 'P6003',
  PROJECT_ALREADY_HAS_MANAGER = 'P6004',
  PROJECT_CANNOT_CHANGE_BUSINESS_UNIT = 'P6005',
  PROJECT_FORBIDDEN = 'P6006',
  PROJECT_ALREADY_ARCHIVED = 'P6007',
  PROJECT_NOT_ARCHIVED = 'P6008',
  PROJECT_INVITATION_NOT_FOUND = 'P6009',
  PROJECT_INVITATION_ALREADY_EXISTS = 'P6010',
  PROJECT_INVITATION_EXPIRED = 'P6011',
  PROJECT_INVITATION_INVALID_TOKEN = 'P6012',
  PROJECT_LAST_MANAGER_CANNOT_BE_DEMOTED = 'P6013',
  PROJECT_LAST_MANAGER_CANNOT_BE_REMOVED = 'P6014',

  // The codes for the sprints app
  SPRINT_NOT_FOUND = 'P7000',
  SPRINT_ALREADY_EXISTS = 'P7001',
  SPRINT_INVALID_DATE_RANGE = 'P7002',
  SPRINT_ALREADY_STARTED = 'P7003',
  SPRINT_ALREADY_COMPLETED = 'P7004',
  SPRINT_HAS_ACTIVE_TASKS = 'P7005',
  SPRINT_INVALID_STATUS_TRANSITION = 'P7006',

  // The codes for the tasks app (Agile)
  TASK_NOT_FOUND = 'P8000',
  TASK_ALREADY_EXISTS = 'P8001',
  TASK_INVALID_STATUS_TRANSITION = 'P8002',
  TASK_CIRCULAR_DEPENDENCY = 'P8003',
  TASK_BLOCKED = 'P8004',
  TASK_WIP_LIMIT_REACHED = 'P8005',

  // The codes for the backlog app
  BACKLOG_NOT_FOUND = 'P8100',
  BACKLOG_INVALID_SPRINT_CAPACITY = 'P8101',

  // The codes for the epics app
  EPIC_NOT_FOUND = 'P8200',
  EPIC_ALREADY_EXISTS = 'P8201',
  EPIC_HAS_LINKED_TASKS = 'P8202',

  // The codes for the milestones app
  MILESTONE_NOT_FOUND = 'P8300',
  MILESTONE_ALREADY_EXISTS = 'P8301',
  MILESTONE_HAS_LINKED_TASKS = 'P8302',

  // The codes for the template system (Agile vs Freestyle)
  PROJECT_NOT_AGILE = 'P8400',
  PROJECT_ALREADY_AGILE = 'P8401',
  AGILE_FEATURE_FORBIDDEN = 'P8402',

  // The codes for the reminders app
  REMINDER_NOT_FOUND = 'P8500',
  REMINDER_ALREADY_EXISTS = 'P8501',
  REMINDER_INVALID_DATE = 'P8502',
  REMINDER_ALREADY_SENT = 'P8503',
  REMINDER_FAILED = 'P8504',
  REMINDER_ALREADY_DISMISSED = 'P8505',
  REMINDER_ALREADY_CANCELLED = 'P8506',

  // The codes for the task labels
  TASK_LABEL_NOT_FOUND = 'P8600',
  TASK_LABEL_ALREADY_EXISTS = 'P8601',
  TASK_LABEL_ALREADY_ASSIGNED = 'P8602',
}
