import { UserType } from '@prisma/client';

export const PERMISSIONS = {
  // Auth
  AUTHS: {
    AUTH_LOGIN: 'auth.login',
    AUTH_LOGOUT: 'auth.logout',
    AUTH_REFRESH: 'auth.refresh',
    AUTH_VERIFY: 'auth.verify',
    AUTH_CREATE_ACCOUNT: 'auth.create.account',

    PASSWORD_RESET_REQUEST: 'password.reset.request',
    PASSWORD_RESET_VERIFY: 'password.reset.verify',
    PASSWORD_RESET: 'password.reset',
  },

  // User accounts
  USERS: {
    USER_CREATE_SELF: 'user.create.self',
    USER_CREATE_BY_ADMIN: 'user.create.by.admin',
    USER_READ_OWN: 'user.read.own',
    USER_READ_BY_ID_BY_MANAGER: 'user.read.by.id.by.manager',
    USER_READ_MANY_BY_MANAGER: 'user.read.many.by.manager',
    USER_UPDATE_SELF: 'user.update.self',
    USER_UPDATE_PASSWORD_SELF: 'user.update.password.self',
    USER_UPDATE_BY_MANAGER: 'user.update.by.manager',
    USER_DELETE: 'user.delete',
    ROLE_READ: 'role.read',
    EMAIL_SEND: 'email.send',
  },

  // Teams
  TEAMS: {
    TEAM_CREATE: 'team.create',
    TEAM_READ_MANY: 'team.read.many',
    TEAM_READ_BY_ID: 'team.read.by.id',
    TEAM_UPDATE: 'team.update',
    TEAM_DELETE: 'team.delete',
  },

  // Events
  EVENTS: {
    EVENT_CREATE: 'event.create',
    EVENT_READ: 'event.read',
    EVENT_UPDATE: 'event.update',
    EVENT_DELETE: 'event.delete',
  },

  // Notifications
  NOTIFICATIONS: {
    NOTIFICATION_TOKEN_CREATE: 'notification.token.create',
    NOTIFICATION_CREATE: 'notification.create',
    NOTIFICATION_UPDATE: 'notification.update',
    NOTIFICATION_READ_FOR_SENDER: 'notification.read.for.sender',
    NOTIFICATION_READ_FOR_RECEIVER: 'notification.read.for.receiver',
    NOTIFICATION_DELETE: 'notification.delete',
  },

  // Personal tasks
  PERSONAL_TASKS: {
    PERSONAL_TASK_CREATE: 'personal.task.create.own',
    PERSONAL_TASK_COMMENT_CREATE: 'personal.task.create.comment.own',
    PERSONAL_TASK_READ_MANY: 'personal.task.read.many.own',
    PERSONAL_TASK_READ_BY_ID: 'personal.task.read.by.id.own',
    PERSONAL_TASK_UPDATE: 'personal.task.update.own',
    PERSONAL_TASK_DELETE: 'personal.task.delete.own',
    PERSONAL_TASK_COMMENT_DELETE: 'personal.task.delete.comment.own',
  },

  // Servers & services
  INFRA: {
    SERVER_CREATE: 'server.create',
    SERVER_UPDATE: 'server.update',
    SERVER_DELETE: 'server.delete',
    SERVER_READ_MANY: 'server.read.many',
    SERVER_READ_BY_ID: 'server.read.by.id',
    SERVICE_CREATE: 'service.create',
    SERVICE_UPDATE: 'service.update',
    SERVICE_DELETE: 'service.delete',
    SERVICE_READ_MANY: 'service.read.many',
    SERVICE_READ_BY_ID: 'service.read.by.id',
  },

  // Work sessions / days
  WORK_SESSIONS: {
    WORK_SESSION_CREATE: 'work.session.create',
    WORK_SESSION_UPDATE_OWN: 'work.session.update.own',
    WORK_SESSION_CLOSE: 'work.session.close',
    WORKDAY_UPDATE_BY_MANAGER: 'workday.update.by.manager',
    WORKDAY_UPDATE_BY_WORKER: 'workday.update.by.worker',
    WORKDAY_READ_OWN: 'workday.read.own',
    WORKDAY_STATISTICS_OVERVIEW_READ_OWN:
      'workday.statistics.overview.read.own',
    WORKDAY_STATISTICS_DETAILS_READ_OWN: 'workday.statistics.details.read.own',
    WORKDAY_STATISTICS_OVERVIEW_READ_BY_MANAGER:
      'workday.statistics.overview.read.by.manager',
    WORKDAY_STATISTICS_DETAILS_READ_BY_MANAGER:
      'workday.statistics.details.read.by.manager',
    WORKDAY_READ_BY_MANAGER: 'workday.read.by.manager',
    WORKDAY_CURRENT_READ_OWN: 'workday.current.read.own',
  },

  // Logs
  LOGS: {
    LOG_FOLDERS_READ: 'log.folders.read',
    LOG_FILE_READ: 'log.file.read',
    LOG_FILE_DOWNLOAD: 'log.file.download',
  },

  // Projects
  PROJECTS: {
    PROJECT_CREATE: 'project.create',
    PROJECT_READ_MANY: 'project.read.many',
    PROJECT_READ_BY_ID: 'project.read.by.id',
    PROJECT_UPDATE: 'project.update',
    PROJECT_DELETE: 'project.delete',
    PROJECT_READ_SUMMARY: 'project.read.summary',
    PROJECT_READ_DETAILS: 'project.read.details',
    PROJECT_ADD_MEMBER: 'project.add.member',
    PROJECT_REMOVE_MEMBER: 'project.remove.member',
    PROJECT_UPDATE_MEMBER: 'project.update.member',
  },

  // Sprints
  SPRINTS: {
    SPRINT_READ: 'sprint.read',
    SPRINT_MANAGE: 'sprint.manage',
  },

  // Tasks (Agile)
  TASKS: {
    TASK_CREATE: 'task.create',
    TASK_READ_MANY: 'task.read.many',
    TASK_READ_BY_ID: 'task.read.by.id',
    TASK_UPDATE_OWN: 'task.update.own',
    TASK_UPDATE_ANY: 'task.update.any',
    TASK_UPDATE_STATUS_OWN: 'task.update.status.own',
    TASK_UPDATE_STATUS_ANY: 'task.update.status.any',
    TASK_ASSIGN: 'task.assign',
    TASK_DELETE: 'task.delete',
    TASK_CREATE_COMMENT: 'task.create.comment',
    TASK_READ_COMMENTS: 'task.read.comments',
    TASK_UPDATE_COMMENT: 'task.update.comment',
    TASK_UPDATE_OWN_COMMENT: 'task.update.own.comment',
    TASK_DELETE_COMMENT: 'task.delete.comment',
    TASK_DELETE_OWN_COMMENT: 'task.delete.own.comment',
    TASK_ADD_DEPENDENCY: 'task.add.dependency',
    TASK_REMOVE_DEPENDENCY: 'task.remove.dependency',
    TASK_LOG_TIME: 'task.log.time',
    TASK_READ_TIME_ENTRIES: 'task.read.time.entries',

    // Task Status Management
    TASK_STATUS_CREATE: 'task.status.create',
    TASK_STATUS_READ: 'task.status.read',
    TASK_STATUS_UPDATE: 'task.status.update',
    TASK_STATUS_DELETE: 'task.status.delete',
    TASK_STATUS_MANAGE: 'task.status.manage', // Full CRUD
    TASK_UPDATE_TIME_ENTRY: 'task.update.time.entry',
    TASK_UPDATE_OWN_TIME_ENTRY: 'task.update.own.time.entry',
    TASK_DELETE_TIME_ENTRY: 'task.delete.time.entry',
    TASK_DELETE_OWN_TIME_ENTRY: 'task.delete.own.time.entry',
    TASK_LIKE_COMMENT: 'task.like.comment',
    TASK_CREATE_LABEL: 'task.create.label',
    TASK_UPDATE_LABEL: 'task.update.label',
    TASK_DELETE_LABEL: 'task.delete.label',
  },

  // Backlog
  BACKLOG: {
    BACKLOG_READ: 'backlog.read',
    BACKLOG_MANAGE: 'backlog.manage',
  },

  // Epics
  EPICS: {
    EPIC_READ: 'epic.read',
    EPIC_MANAGE: 'epic.manage',
  },

  // Milestones
  MILESTONES: {
    MILESTONE_READ: 'milestone.read',
    MILESTONE_MANAGE: 'milestone.manage',
  },

  // Reminders
  REMINDERS: {
    REMINDER_READ: 'reminder.read',
    REMINDER_MANAGE: 'reminder.manage',
    REMINDER_DISMISS_OWN: 'reminder.dismiss.own',
  },
};

export const DEFAULT_PERMISSIONS_FOR_ALL_ROLES = [
  PERMISSIONS.AUTHS.AUTH_LOGIN,
  PERMISSIONS.AUTHS.AUTH_LOGOUT,
  PERMISSIONS.AUTHS.AUTH_REFRESH,
  PERMISSIONS.AUTHS.AUTH_VERIFY,
  PERMISSIONS.AUTHS.PASSWORD_RESET_REQUEST,
  PERMISSIONS.AUTHS.PASSWORD_RESET_VERIFY,
  PERMISSIONS.AUTHS.PASSWORD_RESET,

  PERMISSIONS.USERS.USER_CREATE_SELF,
  PERMISSIONS.USERS.USER_UPDATE_SELF,
  PERMISSIONS.USERS.USER_READ_OWN,
  PERMISSIONS.USERS.EMAIL_SEND,
  PERMISSIONS.USERS.USER_UPDATE_PASSWORD_SELF,

  PERMISSIONS.WORK_SESSIONS.WORK_SESSION_CREATE,
  PERMISSIONS.WORK_SESSIONS.WORK_SESSION_CLOSE,
  PERMISSIONS.WORK_SESSIONS.WORKDAY_UPDATE_BY_WORKER,
  PERMISSIONS.WORK_SESSIONS.WORKDAY_READ_OWN,
  PERMISSIONS.WORK_SESSIONS.WORKDAY_STATISTICS_OVERVIEW_READ_OWN,
  PERMISSIONS.WORK_SESSIONS.WORKDAY_STATISTICS_DETAILS_READ_OWN,
  PERMISSIONS.WORK_SESSIONS.WORKDAY_CURRENT_READ_OWN,

  PERMISSIONS.PERSONAL_TASKS.PERSONAL_TASK_CREATE,
  PERMISSIONS.PERSONAL_TASKS.PERSONAL_TASK_READ_MANY,
  PERMISSIONS.PERSONAL_TASKS.PERSONAL_TASK_READ_BY_ID,
  PERMISSIONS.PERSONAL_TASKS.PERSONAL_TASK_UPDATE,
  PERMISSIONS.PERSONAL_TASKS.PERSONAL_TASK_DELETE,
  PERMISSIONS.PERSONAL_TASKS.PERSONAL_TASK_COMMENT_CREATE,
  PERMISSIONS.PERSONAL_TASKS.PERSONAL_TASK_COMMENT_DELETE,

  PERMISSIONS.NOTIFICATIONS.NOTIFICATION_TOKEN_CREATE,
  PERMISSIONS.NOTIFICATIONS.NOTIFICATION_CREATE,
  PERMISSIONS.NOTIFICATIONS.NOTIFICATION_READ_FOR_SENDER,
  PERMISSIONS.NOTIFICATIONS.NOTIFICATION_READ_FOR_RECEIVER,
  PERMISSIONS.NOTIFICATIONS.NOTIFICATION_UPDATE,
  PERMISSIONS.NOTIFICATIONS.NOTIFICATION_DELETE,

  PERMISSIONS.EVENTS.EVENT_CREATE,
  PERMISSIONS.EVENTS.EVENT_READ,
  PERMISSIONS.EVENTS.EVENT_UPDATE,
  PERMISSIONS.EVENTS.EVENT_DELETE,

  // Projects - Read own projects
  PERMISSIONS.PROJECTS.PROJECT_READ_MANY,
  PERMISSIONS.PROJECTS.PROJECT_READ_BY_ID,
  PERMISSIONS.PROJECTS.PROJECT_READ_SUMMARY,
];

/**
 * Agile permissions for team members (developers, designers, QA, etc.)
 * Execute work inside projects they belong to without taking over
 * planning, moderation, or project administration responsibilities.
 */
const AGILE_TEAM_MEMBER_PERMISSIONS = [
  // Tasks - Read + Update Status Own + Comment + Log Time
  PERMISSIONS.TASKS.TASK_READ_MANY,
  PERMISSIONS.TASKS.TASK_READ_BY_ID,
  PERMISSIONS.TASKS.TASK_UPDATE_STATUS_OWN,
  PERMISSIONS.TASKS.TASK_UPDATE_OWN,
  PERMISSIONS.TASKS.TASK_CREATE_COMMENT,
  PERMISSIONS.TASKS.TASK_READ_COMMENTS,
  PERMISSIONS.TASKS.TASK_UPDATE_OWN_COMMENT,
  PERMISSIONS.TASKS.TASK_DELETE_OWN_COMMENT,
  PERMISSIONS.TASKS.TASK_LIKE_COMMENT,
  PERMISSIONS.TASKS.TASK_LOG_TIME,
  PERMISSIONS.TASKS.TASK_READ_TIME_ENTRIES,
  PERMISSIONS.TASKS.TASK_UPDATE_OWN_TIME_ENTRY,
  PERMISSIONS.TASKS.TASK_DELETE_OWN_TIME_ENTRY,

  // Sprints - Read Access
  PERMISSIONS.SPRINTS.SPRINT_READ,

  // Backlog - Read Access
  PERMISSIONS.BACKLOG.BACKLOG_READ,

  // Epics - Read Access
  PERMISSIONS.EPICS.EPIC_READ,

  // Milestones - Read Access
  PERMISSIONS.MILESTONES.MILESTONE_READ,

  // Reminders - Read Access
  PERMISSIONS.REMINDERS.REMINDER_READ,
  PERMISSIONS.REMINDERS.REMINDER_DISMISS_OWN,
];

/**
 * Product Owner focuses on backlog ownership and task shaping.
 * Sprint execution remains visible, but sprint administration stays with PM/SM.
 */
const PRODUCT_OWNER_PERMISSIONS = [
  PERMISSIONS.SPRINTS.SPRINT_READ,

  PERMISSIONS.TASKS.TASK_CREATE,
  PERMISSIONS.TASKS.TASK_READ_MANY,
  PERMISSIONS.TASKS.TASK_READ_BY_ID,
  PERMISSIONS.TASKS.TASK_UPDATE_ANY,
  PERMISSIONS.TASKS.TASK_UPDATE_STATUS_ANY,
  PERMISSIONS.TASKS.TASK_ASSIGN,
  PERMISSIONS.TASKS.TASK_DELETE,
  PERMISSIONS.TASKS.TASK_CREATE_COMMENT,
  PERMISSIONS.TASKS.TASK_READ_COMMENTS,
  PERMISSIONS.TASKS.TASK_UPDATE_COMMENT,
  PERMISSIONS.TASKS.TASK_DELETE_COMMENT,
  PERMISSIONS.TASKS.TASK_LIKE_COMMENT,
  PERMISSIONS.TASKS.TASK_ADD_DEPENDENCY,
  PERMISSIONS.TASKS.TASK_REMOVE_DEPENDENCY,
  PERMISSIONS.TASKS.TASK_READ_TIME_ENTRIES,
  PERMISSIONS.TASKS.TASK_UPDATE_TIME_ENTRY,
  PERMISSIONS.TASKS.TASK_DELETE_TIME_ENTRY,
  PERMISSIONS.TASKS.TASK_CREATE_LABEL,
  PERMISSIONS.TASKS.TASK_UPDATE_LABEL,
  PERMISSIONS.TASKS.TASK_DELETE_LABEL,

  PERMISSIONS.BACKLOG.BACKLOG_READ,
  PERMISSIONS.BACKLOG.BACKLOG_MANAGE,

  PERMISSIONS.EPICS.EPIC_READ,
  PERMISSIONS.EPICS.EPIC_MANAGE,

  PERMISSIONS.MILESTONES.MILESTONE_READ,
  PERMISSIONS.MILESTONES.MILESTONE_MANAGE,

  PERMISSIONS.REMINDERS.REMINDER_READ,
  PERMISSIONS.REMINDERS.REMINDER_MANAGE,
  PERMISSIONS.REMINDERS.REMINDER_DISMISS_OWN,
];

/**
 * Scrum Master facilitates sprints and board flow rather than owning
 * project setup or product backlog prioritization.
 */
const SCRUM_MASTER_PERMISSIONS = [
  PERMISSIONS.SPRINTS.SPRINT_READ,
  PERMISSIONS.SPRINTS.SPRINT_MANAGE,

  PERMISSIONS.TASKS.TASK_READ_MANY,
  PERMISSIONS.TASKS.TASK_READ_BY_ID,
  PERMISSIONS.TASKS.TASK_UPDATE_STATUS_ANY,
  PERMISSIONS.TASKS.TASK_UPDATE_ANY,
  PERMISSIONS.TASKS.TASK_ASSIGN,
  PERMISSIONS.TASKS.TASK_CREATE_COMMENT,
  PERMISSIONS.TASKS.TASK_READ_COMMENTS,
  PERMISSIONS.TASKS.TASK_UPDATE_OWN_COMMENT,
  PERMISSIONS.TASKS.TASK_DELETE_OWN_COMMENT,
  PERMISSIONS.TASKS.TASK_LIKE_COMMENT,
  PERMISSIONS.TASKS.TASK_READ_TIME_ENTRIES,

  PERMISSIONS.BACKLOG.BACKLOG_READ,
  PERMISSIONS.BACKLOG.BACKLOG_MANAGE,

  PERMISSIONS.EPICS.EPIC_READ,
  PERMISSIONS.MILESTONES.MILESTONE_READ,
  PERMISSIONS.REMINDERS.REMINDER_READ,
  PERMISSIONS.REMINDERS.REMINDER_DISMISS_OWN,
];

/**
 * Business Analyst can capture and discuss work items without taking over
 * sprint administration or execution management.
 */
const BUSINESS_ANALYST_PERMISSIONS = [
  PERMISSIONS.SPRINTS.SPRINT_READ,

  PERMISSIONS.TASKS.TASK_CREATE,
  PERMISSIONS.TASKS.TASK_READ_MANY,
  PERMISSIONS.TASKS.TASK_READ_BY_ID,
  PERMISSIONS.TASKS.TASK_CREATE_COMMENT,
  PERMISSIONS.TASKS.TASK_READ_COMMENTS,
  PERMISSIONS.TASKS.TASK_UPDATE_OWN_COMMENT,
  PERMISSIONS.TASKS.TASK_DELETE_OWN_COMMENT,
  PERMISSIONS.TASKS.TASK_LIKE_COMMENT,

  PERMISSIONS.BACKLOG.BACKLOG_READ,

  PERMISSIONS.EPICS.EPIC_READ,
  PERMISSIONS.MILESTONES.MILESTONE_READ,
  PERMISSIONS.REMINDERS.REMINDER_READ,
  PERMISSIONS.REMINDERS.REMINDER_DISMISS_OWN,
];

export const PERMISSIONS_FOR_ROLE = {
  // 👔 Executive
  [UserType.CEO]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat([
    PERMISSIONS.USERS.USER_CREATE_BY_ADMIN,
    PERMISSIONS.USERS.USER_DELETE,
    PERMISSIONS.USERS.ROLE_READ,
    PERMISSIONS.USERS.USER_UPDATE_BY_MANAGER,
    PERMISSIONS.USERS.USER_READ_BY_ID_BY_MANAGER,
    PERMISSIONS.USERS.USER_READ_MANY_BY_MANAGER,

    PERMISSIONS.WORK_SESSIONS.WORKDAY_STATISTICS_DETAILS_READ_BY_MANAGER,
    PERMISSIONS.WORK_SESSIONS.WORKDAY_STATISTICS_OVERVIEW_READ_BY_MANAGER,

    PERMISSIONS.TEAMS.TEAM_CREATE,
    PERMISSIONS.TEAMS.TEAM_READ_MANY,
    PERMISSIONS.TEAMS.TEAM_READ_BY_ID,
    PERMISSIONS.TEAMS.TEAM_UPDATE,
    PERMISSIONS.TEAMS.TEAM_DELETE,

    PERMISSIONS.INFRA.SERVER_READ_MANY,
    PERMISSIONS.INFRA.SERVER_READ_BY_ID,
    PERMISSIONS.INFRA.SERVICE_READ_MANY,
    PERMISSIONS.INFRA.SERVICE_READ_BY_ID,

    // Projects - Full Access
    PERMISSIONS.PROJECTS.PROJECT_CREATE,
    PERMISSIONS.PROJECTS.PROJECT_READ_MANY,
    PERMISSIONS.PROJECTS.PROJECT_READ_BY_ID,
    PERMISSIONS.PROJECTS.PROJECT_UPDATE,
    PERMISSIONS.PROJECTS.PROJECT_DELETE,
    PERMISSIONS.PROJECTS.PROJECT_READ_SUMMARY,
    PERMISSIONS.PROJECTS.PROJECT_READ_DETAILS,
    PERMISSIONS.PROJECTS.PROJECT_ADD_MEMBER,
    PERMISSIONS.PROJECTS.PROJECT_REMOVE_MEMBER,
    PERMISSIONS.PROJECTS.PROJECT_UPDATE_MEMBER,

    // Sprints - Full Access
    PERMISSIONS.SPRINTS.SPRINT_READ,
    PERMISSIONS.SPRINTS.SPRINT_MANAGE,

    // Tasks - Full Access
    PERMISSIONS.TASKS.TASK_CREATE,
    PERMISSIONS.TASKS.TASK_READ_MANY,
    PERMISSIONS.TASKS.TASK_READ_BY_ID,
    PERMISSIONS.TASKS.TASK_UPDATE_ANY,
    PERMISSIONS.TASKS.TASK_UPDATE_STATUS_ANY,
    PERMISSIONS.TASKS.TASK_ASSIGN,
    PERMISSIONS.TASKS.TASK_DELETE,
    PERMISSIONS.TASKS.TASK_CREATE_COMMENT,
    PERMISSIONS.TASKS.TASK_READ_COMMENTS,
    PERMISSIONS.TASKS.TASK_UPDATE_COMMENT,
    PERMISSIONS.TASKS.TASK_LIKE_COMMENT,
    PERMISSIONS.TASKS.TASK_DELETE_COMMENT,
    PERMISSIONS.TASKS.TASK_ADD_DEPENDENCY,
    PERMISSIONS.TASKS.TASK_REMOVE_DEPENDENCY,
    PERMISSIONS.TASKS.TASK_LOG_TIME,
    PERMISSIONS.TASKS.TASK_READ_TIME_ENTRIES,
    PERMISSIONS.TASKS.TASK_UPDATE_TIME_ENTRY,
    PERMISSIONS.TASKS.TASK_DELETE_TIME_ENTRY,
    PERMISSIONS.TASKS.TASK_CREATE_LABEL,
    PERMISSIONS.TASKS.TASK_UPDATE_LABEL,
    PERMISSIONS.TASKS.TASK_DELETE_LABEL,

    // Task Status Management - Full Access
    PERMISSIONS.TASKS.TASK_STATUS_MANAGE,

    // Backlog - Full Access
    PERMISSIONS.BACKLOG.BACKLOG_READ,
    PERMISSIONS.BACKLOG.BACKLOG_MANAGE,

    // Epics - Full Access
    PERMISSIONS.EPICS.EPIC_MANAGE,
    PERMISSIONS.EPICS.EPIC_READ,

    // Milestones - Full Access
    PERMISSIONS.MILESTONES.MILESTONE_MANAGE,
    PERMISSIONS.MILESTONES.MILESTONE_READ,

    // Task Status Management - Full Access
    PERMISSIONS.TASKS.TASK_STATUS_MANAGE,

    // Reminders - Full Access
    PERMISSIONS.REMINDERS.REMINDER_MANAGE,
    PERMISSIONS.REMINDERS.REMINDER_READ,
  ]),
  [UserType.CTO]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat([
    PERMISSIONS.USERS.USER_CREATE_BY_ADMIN,
    PERMISSIONS.USERS.USER_UPDATE_BY_MANAGER,
    PERMISSIONS.USERS.USER_DELETE,
    PERMISSIONS.USERS.ROLE_READ,
    PERMISSIONS.USERS.USER_READ_BY_ID_BY_MANAGER,
    PERMISSIONS.USERS.USER_READ_MANY_BY_MANAGER,

    PERMISSIONS.WORK_SESSIONS.WORKDAY_STATISTICS_DETAILS_READ_BY_MANAGER,
    PERMISSIONS.WORK_SESSIONS.WORKDAY_STATISTICS_OVERVIEW_READ_BY_MANAGER,

    PERMISSIONS.TEAMS.TEAM_CREATE,
    PERMISSIONS.TEAMS.TEAM_READ_MANY,
    PERMISSIONS.TEAMS.TEAM_READ_BY_ID,
    PERMISSIONS.TEAMS.TEAM_UPDATE,
    PERMISSIONS.TEAMS.TEAM_DELETE,

    PERMISSIONS.INFRA.SERVER_CREATE,
    PERMISSIONS.INFRA.SERVER_UPDATE,
    PERMISSIONS.INFRA.SERVER_DELETE,
    PERMISSIONS.INFRA.SERVER_READ_MANY,
    PERMISSIONS.INFRA.SERVICE_CREATE,
    PERMISSIONS.INFRA.SERVICE_UPDATE,
    PERMISSIONS.INFRA.SERVICE_DELETE,
    PERMISSIONS.INFRA.SERVICE_READ_MANY,
    PERMISSIONS.INFRA.SERVICE_READ_BY_ID,
    PERMISSIONS.INFRA.SERVER_READ_BY_ID,

    PERMISSIONS.LOGS.LOG_FOLDERS_READ,
    PERMISSIONS.LOGS.LOG_FILE_READ,
    PERMISSIONS.LOGS.LOG_FILE_DOWNLOAD,

    // Projects - Full Access (TawerDev only)
    PERMISSIONS.PROJECTS.PROJECT_CREATE,
    PERMISSIONS.PROJECTS.PROJECT_READ_MANY,
    PERMISSIONS.PROJECTS.PROJECT_READ_BY_ID,
    PERMISSIONS.PROJECTS.PROJECT_UPDATE,
    PERMISSIONS.PROJECTS.PROJECT_DELETE,
    PERMISSIONS.PROJECTS.PROJECT_READ_SUMMARY,
    PERMISSIONS.PROJECTS.PROJECT_READ_DETAILS,
    PERMISSIONS.PROJECTS.PROJECT_ADD_MEMBER,
    PERMISSIONS.PROJECTS.PROJECT_REMOVE_MEMBER,
    PERMISSIONS.PROJECTS.PROJECT_UPDATE_MEMBER,

    // Tasks - Full Access
    PERMISSIONS.TASKS.TASK_CREATE,
    PERMISSIONS.TASKS.TASK_READ_MANY,
    PERMISSIONS.TASKS.TASK_READ_BY_ID,
    PERMISSIONS.TASKS.TASK_UPDATE_ANY,
    PERMISSIONS.TASKS.TASK_UPDATE_STATUS_ANY,
    PERMISSIONS.TASKS.TASK_ASSIGN,
    PERMISSIONS.TASKS.TASK_DELETE,
    PERMISSIONS.TASKS.TASK_CREATE_COMMENT,
    PERMISSIONS.TASKS.TASK_READ_COMMENTS,
    PERMISSIONS.TASKS.TASK_UPDATE_COMMENT,
    PERMISSIONS.TASKS.TASK_LIKE_COMMENT,
    PERMISSIONS.TASKS.TASK_DELETE_COMMENT,
    PERMISSIONS.TASKS.TASK_ADD_DEPENDENCY,
    PERMISSIONS.TASKS.TASK_REMOVE_DEPENDENCY,
    PERMISSIONS.TASKS.TASK_LOG_TIME,
    PERMISSIONS.TASKS.TASK_READ_TIME_ENTRIES,
    PERMISSIONS.TASKS.TASK_UPDATE_TIME_ENTRY,
    PERMISSIONS.TASKS.TASK_DELETE_TIME_ENTRY,
    PERMISSIONS.TASKS.TASK_CREATE_LABEL,
    PERMISSIONS.TASKS.TASK_UPDATE_LABEL,
    PERMISSIONS.TASKS.TASK_DELETE_LABEL,

    // Sprints - Full Access
    PERMISSIONS.SPRINTS.SPRINT_READ,
    PERMISSIONS.SPRINTS.SPRINT_MANAGE,

    // Backlog - Full Access
    PERMISSIONS.BACKLOG.BACKLOG_READ,
    PERMISSIONS.BACKLOG.BACKLOG_MANAGE,

    // Epics - Full Access
    PERMISSIONS.EPICS.EPIC_MANAGE,
    PERMISSIONS.EPICS.EPIC_READ,

    // Milestones - Full Access
    PERMISSIONS.MILESTONES.MILESTONE_MANAGE,
    PERMISSIONS.MILESTONES.MILESTONE_READ,

    // Reminders - Full Access
    PERMISSIONS.REMINDERS.REMINDER_MANAGE,
    PERMISSIONS.REMINDERS.REMINDER_READ,
  ]),
  [UserType.CMO]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat([
    PERMISSIONS.USERS.USER_CREATE_BY_ADMIN,
    PERMISSIONS.USERS.USER_DELETE,
    PERMISSIONS.USERS.ROLE_READ,
    PERMISSIONS.USERS.USER_READ_BY_ID_BY_MANAGER,
    PERMISSIONS.USERS.USER_READ_MANY_BY_MANAGER,

    PERMISSIONS.WORK_SESSIONS.WORKDAY_STATISTICS_DETAILS_READ_BY_MANAGER,
    PERMISSIONS.WORK_SESSIONS.WORKDAY_STATISTICS_OVERVIEW_READ_BY_MANAGER,

    PERMISSIONS.TEAMS.TEAM_CREATE,
    PERMISSIONS.TEAMS.TEAM_READ_MANY,
    PERMISSIONS.TEAMS.TEAM_READ_BY_ID,
    PERMISSIONS.TEAMS.TEAM_UPDATE,
    PERMISSIONS.TEAMS.TEAM_DELETE,

    // Projects - Full Access (TawerCreative only)
    PERMISSIONS.PROJECTS.PROJECT_CREATE,
    PERMISSIONS.PROJECTS.PROJECT_READ_MANY,
    PERMISSIONS.PROJECTS.PROJECT_READ_BY_ID,
    PERMISSIONS.PROJECTS.PROJECT_UPDATE,
    PERMISSIONS.PROJECTS.PROJECT_DELETE,
    PERMISSIONS.PROJECTS.PROJECT_READ_SUMMARY,
    PERMISSIONS.PROJECTS.PROJECT_READ_DETAILS,
    PERMISSIONS.PROJECTS.PROJECT_ADD_MEMBER,
    PERMISSIONS.PROJECTS.PROJECT_REMOVE_MEMBER,
    PERMISSIONS.PROJECTS.PROJECT_UPDATE_MEMBER,

    // Tasks - Full Access
    PERMISSIONS.TASKS.TASK_CREATE,
    PERMISSIONS.TASKS.TASK_READ_MANY,
    PERMISSIONS.TASKS.TASK_READ_BY_ID,
    PERMISSIONS.TASKS.TASK_UPDATE_ANY,
    PERMISSIONS.TASKS.TASK_UPDATE_STATUS_ANY,
    PERMISSIONS.TASKS.TASK_ASSIGN,
    PERMISSIONS.TASKS.TASK_DELETE,
    PERMISSIONS.TASKS.TASK_CREATE_COMMENT,
    PERMISSIONS.TASKS.TASK_READ_COMMENTS,
    PERMISSIONS.TASKS.TASK_UPDATE_COMMENT,
    PERMISSIONS.TASKS.TASK_LIKE_COMMENT,
    PERMISSIONS.TASKS.TASK_DELETE_COMMENT,
    PERMISSIONS.TASKS.TASK_ADD_DEPENDENCY,
    PERMISSIONS.TASKS.TASK_REMOVE_DEPENDENCY,
    PERMISSIONS.TASKS.TASK_LOG_TIME,
    PERMISSIONS.TASKS.TASK_READ_TIME_ENTRIES,
    PERMISSIONS.TASKS.TASK_UPDATE_TIME_ENTRY,
    PERMISSIONS.TASKS.TASK_DELETE_TIME_ENTRY,
    PERMISSIONS.TASKS.TASK_CREATE_LABEL,
    PERMISSIONS.TASKS.TASK_UPDATE_LABEL,
    PERMISSIONS.TASKS.TASK_DELETE_LABEL,

    // Sprints - Full Access
    PERMISSIONS.SPRINTS.SPRINT_READ,
    PERMISSIONS.SPRINTS.SPRINT_MANAGE,

    // Backlog - Full Access
    PERMISSIONS.BACKLOG.BACKLOG_READ,
    PERMISSIONS.BACKLOG.BACKLOG_MANAGE,

    // Epics - Full Access
    PERMISSIONS.EPICS.EPIC_MANAGE,
    PERMISSIONS.EPICS.EPIC_READ,

    // Milestones - Full Access
    PERMISSIONS.MILESTONES.MILESTONE_MANAGE,
    PERMISSIONS.MILESTONES.MILESTONE_READ,

    // Reminders - Full Access
    PERMISSIONS.REMINDERS.REMINDER_MANAGE,
    PERMISSIONS.REMINDERS.REMINDER_READ,
  ]),

  // 🎨 Tawer Creative
  [UserType.TawerCreativeProjectManager]:
    DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat([
      PERMISSIONS.WORK_SESSIONS.WORKDAY_READ_BY_MANAGER,
      PERMISSIONS.WORK_SESSIONS.WORKDAY_UPDATE_BY_MANAGER,
      PERMISSIONS.WORK_SESSIONS.WORKDAY_STATISTICS_DETAILS_READ_BY_MANAGER,
      PERMISSIONS.WORK_SESSIONS.WORKDAY_STATISTICS_OVERVIEW_READ_BY_MANAGER,

      PERMISSIONS.USERS.USER_READ_BY_ID_BY_MANAGER,
      PERMISSIONS.USERS.USER_READ_MANY_BY_MANAGER,

      // Projects - Manage own projects
      PERMISSIONS.PROJECTS.PROJECT_READ_MANY,
      PERMISSIONS.PROJECTS.PROJECT_READ_BY_ID,
      PERMISSIONS.PROJECTS.PROJECT_UPDATE,
      PERMISSIONS.PROJECTS.PROJECT_DELETE,
      PERMISSIONS.PROJECTS.PROJECT_READ_SUMMARY,
      PERMISSIONS.PROJECTS.PROJECT_READ_DETAILS,
      PERMISSIONS.PROJECTS.PROJECT_ADD_MEMBER,
      PERMISSIONS.PROJECTS.PROJECT_REMOVE_MEMBER,
      PERMISSIONS.PROJECTS.PROJECT_UPDATE_MEMBER,

      // Sprints - Full Access
      PERMISSIONS.SPRINTS.SPRINT_READ,
      PERMISSIONS.SPRINTS.SPRINT_MANAGE,

      // Tasks - Full Access
      PERMISSIONS.TASKS.TASK_CREATE,
      PERMISSIONS.TASKS.TASK_READ_MANY,
      PERMISSIONS.TASKS.TASK_READ_BY_ID,
      PERMISSIONS.TASKS.TASK_UPDATE_ANY,
      PERMISSIONS.TASKS.TASK_UPDATE_STATUS_ANY,
      PERMISSIONS.TASKS.TASK_ASSIGN,
      PERMISSIONS.TASKS.TASK_DELETE,
      PERMISSIONS.TASKS.TASK_CREATE_COMMENT,
      PERMISSIONS.TASKS.TASK_READ_COMMENTS,
      PERMISSIONS.TASKS.TASK_UPDATE_COMMENT,
      PERMISSIONS.TASKS.TASK_LIKE_COMMENT,
      PERMISSIONS.TASKS.TASK_DELETE_COMMENT,
      PERMISSIONS.TASKS.TASK_ADD_DEPENDENCY,
      PERMISSIONS.TASKS.TASK_REMOVE_DEPENDENCY,
      PERMISSIONS.TASKS.TASK_LOG_TIME,
      PERMISSIONS.TASKS.TASK_READ_TIME_ENTRIES,
      PERMISSIONS.TASKS.TASK_UPDATE_TIME_ENTRY,
      PERMISSIONS.TASKS.TASK_DELETE_TIME_ENTRY,
      PERMISSIONS.TASKS.TASK_CREATE_LABEL,
      PERMISSIONS.TASKS.TASK_UPDATE_LABEL,
      PERMISSIONS.TASKS.TASK_DELETE_LABEL,

      // Backlog - Full Access
      PERMISSIONS.BACKLOG.BACKLOG_READ,
      PERMISSIONS.BACKLOG.BACKLOG_MANAGE,

      // Epics - Full Access
      PERMISSIONS.EPICS.EPIC_MANAGE,
      PERMISSIONS.EPICS.EPIC_READ,

      // Milestones - Full Access
      PERMISSIONS.MILESTONES.MILESTONE_MANAGE,
      PERMISSIONS.MILESTONES.MILESTONE_READ,

      // Reminders - Full Access
      PERMISSIONS.REMINDERS.REMINDER_MANAGE,
      PERMISSIONS.REMINDERS.REMINDER_READ,
    ]),
  [UserType.GraphicDesigner]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.SocialMediaManager]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.ContentWriter]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.VideoEditor]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.UiUxDesigner]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),

  // 💻 Tawer Dev
  [UserType.TawerDevProjectManager]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat([
    PERMISSIONS.USERS.USER_READ_BY_ID_BY_MANAGER,
    PERMISSIONS.USERS.USER_READ_MANY_BY_MANAGER,
    PERMISSIONS.WORK_SESSIONS.WORKDAY_STATISTICS_DETAILS_READ_BY_MANAGER,
    PERMISSIONS.WORK_SESSIONS.WORKDAY_STATISTICS_OVERVIEW_READ_BY_MANAGER,

    PERMISSIONS.WORK_SESSIONS.WORKDAY_READ_BY_MANAGER,
    PERMISSIONS.WORK_SESSIONS.WORKDAY_UPDATE_BY_MANAGER,

    // Projects - Manage own projects
    PERMISSIONS.PROJECTS.PROJECT_READ_MANY,
    PERMISSIONS.PROJECTS.PROJECT_READ_BY_ID,
    PERMISSIONS.PROJECTS.PROJECT_UPDATE,
    PERMISSIONS.PROJECTS.PROJECT_DELETE,
    PERMISSIONS.PROJECTS.PROJECT_READ_SUMMARY,
    PERMISSIONS.PROJECTS.PROJECT_READ_DETAILS,
    PERMISSIONS.PROJECTS.PROJECT_ADD_MEMBER,
    PERMISSIONS.PROJECTS.PROJECT_REMOVE_MEMBER,
    PERMISSIONS.PROJECTS.PROJECT_UPDATE_MEMBER,

    // Sprints - Full Access
    PERMISSIONS.SPRINTS.SPRINT_READ,
    PERMISSIONS.SPRINTS.SPRINT_MANAGE,

    // Tasks - Full Access
    PERMISSIONS.TASKS.TASK_CREATE,
    PERMISSIONS.TASKS.TASK_READ_MANY,
    PERMISSIONS.TASKS.TASK_READ_BY_ID,
    PERMISSIONS.TASKS.TASK_UPDATE_ANY,
    PERMISSIONS.TASKS.TASK_DELETE,
    PERMISSIONS.TASKS.TASK_UPDATE_STATUS_ANY,
    PERMISSIONS.TASKS.TASK_CREATE_COMMENT,
    PERMISSIONS.TASKS.TASK_READ_COMMENTS,
    PERMISSIONS.TASKS.TASK_UPDATE_COMMENT,
    PERMISSIONS.TASKS.TASK_LIKE_COMMENT,
    PERMISSIONS.TASKS.TASK_DELETE_COMMENT,
    PERMISSIONS.TASKS.TASK_ADD_DEPENDENCY,
    PERMISSIONS.TASKS.TASK_REMOVE_DEPENDENCY,
    PERMISSIONS.TASKS.TASK_LOG_TIME,
    PERMISSIONS.TASKS.TASK_READ_TIME_ENTRIES,
    PERMISSIONS.TASKS.TASK_UPDATE_TIME_ENTRY,
    PERMISSIONS.TASKS.TASK_DELETE_TIME_ENTRY,
    PERMISSIONS.TASKS.TASK_CREATE_LABEL,
    PERMISSIONS.TASKS.TASK_UPDATE_LABEL,
    PERMISSIONS.TASKS.TASK_DELETE_LABEL,

    // Backlog - Full Access
    PERMISSIONS.BACKLOG.BACKLOG_READ,
    PERMISSIONS.BACKLOG.BACKLOG_MANAGE,

    // Epics - Full Access
    PERMISSIONS.EPICS.EPIC_MANAGE,
    PERMISSIONS.EPICS.EPIC_READ,

    // Milestones - Full Access
    PERMISSIONS.MILESTONES.MILESTONE_MANAGE,
    PERMISSIONS.MILESTONES.MILESTONE_READ,

    // Reminders - Full Access
    PERMISSIONS.REMINDERS.REMINDER_MANAGE,
    PERMISSIONS.REMINDERS.REMINDER_READ,
  ]),
  [UserType.SoftwareEngineer]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.DataEngineer]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.DevopsEngineer]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat([
    PERMISSIONS.INFRA.SERVER_READ_BY_ID,
    PERMISSIONS.INFRA.SERVER_READ_MANY,
    PERMISSIONS.INFRA.SERVICE_READ_BY_ID,
    PERMISSIONS.INFRA.SERVICE_READ_MANY,
    PERMISSIONS.INFRA.SERVER_UPDATE,
    PERMISSIONS.INFRA.SERVER_DELETE,
    PERMISSIONS.INFRA.SERVICE_DELETE,
    PERMISSIONS.INFRA.SERVICE_UPDATE,
    PERMISSIONS.INFRA.SERVER_CREATE,

    PERMISSIONS.LOGS.LOG_FOLDERS_READ,
    PERMISSIONS.LOGS.LOG_FILE_READ,
    PERMISSIONS.LOGS.LOG_FILE_DOWNLOAD,
  ]).concat(AGILE_TEAM_MEMBER_PERMISSIONS),
  [UserType.QualityAssuranceEngineer]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.ProductOwner]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat([
    ...PRODUCT_OWNER_PERMISSIONS,
  ]),
  [UserType.ScrumMaster]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat([
    ...SCRUM_MASTER_PERMISSIONS,
  ]),
  [UserType.BusinessAnalyst]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat([
    ...BUSINESS_ANALYST_PERMISSIONS,
  ]),
  [UserType.MobileAppDeveloper]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.FrontendDeveloper]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.BackendDeveloper]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.FullStackDeveloper]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.DatabaseAdministrator]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.SystemsArchitect]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.NetworkEngineer]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.CyberSecuritySpecialist]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.SeoSpecialist]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),
  [UserType.CustomerSupport]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES.concat(
    AGILE_TEAM_MEMBER_PERMISSIONS,
  ),

  // 🧑‍💼 Human Resources
  [UserType.HRManager]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES,

  // ⏳ Default / pending
  [UserType.PendingApproval]: [
    PERMISSIONS.AUTHS.AUTH_LOGIN,
    PERMISSIONS.AUTHS.AUTH_LOGOUT,
    PERMISSIONS.AUTHS.AUTH_REFRESH,
    PERMISSIONS.AUTHS.AUTH_VERIFY,
    PERMISSIONS.AUTHS.AUTH_CREATE_ACCOUNT,
    PERMISSIONS.AUTHS.PASSWORD_RESET_REQUEST,
    PERMISSIONS.AUTHS.PASSWORD_RESET_VERIFY,
    PERMISSIONS.AUTHS.PASSWORD_RESET,
  ],

  // 🎓 Interns
  [UserType.TawerCreativeIntern]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES,
  [UserType.TawerDevIntern]: DEFAULT_PERMISSIONS_FOR_ALL_ROLES,
};

export const ALL_ROLES: UserType[] = Object.values(UserType);
export const EXECUTIVE_ROLES: UserType[] = [
  UserType.CEO,
  UserType.CTO,
  UserType.CMO,
];
export const MANAGER_ROLES: UserType[] = [
  UserType.TawerCreativeProjectManager,
  UserType.TawerDevProjectManager,
];
export const INTERN_ROLES: UserType[] = [
  UserType.TawerCreativeIntern,
  UserType.TawerDevIntern,
];
export const EXECUTIVE_MANAGER_ROLES: UserType[] = [
  ...EXECUTIVE_ROLES,
  ...MANAGER_ROLES,
];

export const ROLE_MANAGE_ROLES: { [key in UserType]?: UserType[] } = {
  [UserType.CEO]: ALL_ROLES,
  [UserType.CTO]: ALL_ROLES,
  [UserType.CMO]: ALL_ROLES,
  [UserType.TawerCreativeProjectManager]: [
    UserType.GraphicDesigner,
    UserType.SocialMediaManager,
    UserType.ContentWriter,
    UserType.VideoEditor,
    UserType.UiUxDesigner,
    UserType.TawerCreativeIntern,
  ],
  [UserType.TawerDevProjectManager]: [
    UserType.SoftwareEngineer,
    UserType.DataEngineer,
    UserType.DevopsEngineer,
    UserType.QualityAssuranceEngineer,
    UserType.ProductOwner,
    UserType.ScrumMaster,
    UserType.BusinessAnalyst,
    UserType.MobileAppDeveloper,
    UserType.FrontendDeveloper,
    UserType.BackendDeveloper,
    UserType.FullStackDeveloper,
    UserType.DatabaseAdministrator,
    UserType.SystemsArchitect,
    UserType.NetworkEngineer,
    UserType.CyberSecuritySpecialist,
    UserType.SeoSpecialist,
    UserType.CustomerSupport,
    UserType.TawerDevIntern,
  ],
  [UserType.HRManager]: ALL_ROLES.filter(
    (role) =>
      role !== UserType.CEO && role !== UserType.CTO && role !== UserType.CMO,
  ),
  [UserType.PendingApproval]: [],
  [UserType.TawerCreativeIntern]: [],
  [UserType.TawerDevIntern]: [],
  [UserType.GraphicDesigner]: [],
  [UserType.SocialMediaManager]: [],
  [UserType.ContentWriter]: [],
  [UserType.VideoEditor]: [],
  [UserType.UiUxDesigner]: [],
  [UserType.SoftwareEngineer]: [],
  [UserType.DataEngineer]: [],
  [UserType.DevopsEngineer]: [],
  [UserType.QualityAssuranceEngineer]: [],
  [UserType.ProductOwner]: [],
  [UserType.ScrumMaster]: [],
  [UserType.BusinessAnalyst]: [],
  [UserType.MobileAppDeveloper]: [],
  [UserType.FrontendDeveloper]: [],
  [UserType.BackendDeveloper]: [],
  [UserType.FullStackDeveloper]: [],
  [UserType.DatabaseAdministrator]: [],
  [UserType.SystemsArchitect]: [],
  [UserType.NetworkEngineer]: [],
  [UserType.CyberSecuritySpecialist]: [],
  [UserType.SeoSpecialist]: [],
  [UserType.CustomerSupport]: [],
};
